### ISSUE TITLE
Typo label input

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#1]
![Screenshot (126)](https://github.com/MuhammadSonySetiawan/hirejob/assets/49361887/a4a70b4a-961b-46bd-9a15-3a7a6ae10935)

Fix typo label

**Comment by MuhammadSonySetiawan** [comment]
fixed typo text to "nomor telepon"
![screencapture-hirejob-ep6k-vercel-app-register-2023-08-08-00_21_18](https://github.com/MuhammadSonySetiawan/hirejob/assets/132990489/ef10fc6f-e6b5-4436-8a85-3dede75d4788)
