### ISSUE TITLE
Got error email already in used but error not user friendly

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#2]
Please fix your error message get from backend to improve your user experience
![Screenshot (127)](https://github.com/MuhammadSonySetiawan/hirejob/assets/49361887/313c030a-7c69-42b2-b974-9d043404db1e)

**Comment by MuhammadSonySetiawan** [comment]
repair messages from backand
![Screenshot 2023-08-08 002628](https://github.com/MuhammadSonySetiawan/hirejob/assets/132990489/b4974e58-31d7-46d5-bbbc-134bef15ef91)

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-10 at 11 04 27" src="https://github.com/MuhammadSonySetiawan/Peworld/assets/49361887/82b3bbc8-7e8c-4be3-85ff-ff1dd0eb3b8f">

Errornya berubah jadi gini kalo misal job titlenya kepanjangan

**Comment by MuhammadSonySetiawan** [comment]
job title length validation
![Screenshot 2023-08-10 115221](https://github.com/MuhammadSonySetiawan/Peworld/assets/132990489/bb9adfc4-52ed-458d-9bb5-cf344eea00b1)
