### ISSUE TITLE
Add loading indicator in button

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#3]
Add loading indicator in every button

**Comment by MuhammadSonySetiawan** [comment]
Add loading indicator in button
![screencapture-hirejob-ep6k-vercel-app-register-2023-08-08-00_25_01](https://github.com/MuhammadSonySetiawan/hirejob/assets/132990489/9aabf619-a8f0-4500-b8f7-6904a5f00dbb)
