### ISSUE TITLE
Please change button name change photo profile

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#4]
![Screenshot (128)](https://github.com/MuhammadSonySetiawan/hirejob/assets/49361887/40053bd9-9a6f-4c35-86d7-c898903eb8e2)

Please change button edit to change photo profile

**Comment by MuhammadSonySetiawan** [comment]
rename the photo edit button to "edit foto profile"
![Screenshot 2023-08-08 003232](https://github.com/MuhammadSonySetiawan/hirejob/assets/132990489/55df3ddc-a23b-4542-9732-9d7a064b960c)
