### ISSUE TITLE
Got error in add job experience

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#5]
If i not complete the form field i got error in network but in app not showing anything, please fix if i got error show in frontend

![Screenshot (129)](https://github.com/MuhammadSonySetiawan/hirejob/assets/49361887/7ae0a4f6-c65c-4b5c-b367-97dd556b14cc)

**Comment by MuhammadSonySetiawan** [comment]
adding validation to input text
![Screenshot 2023-08-08 003854](https://github.com/MuhammadSonySetiawan/hirejob/assets/132990489/c499e0c7-3788-42e2-826a-f521fe13a2ab)
