### ISSUE TITLE
Wrong password but got something wrong in our server

### ISSUE THREAD

**Issue by kubil-ismail** [MuhammadSonySetiawan/Peworld#7]
<img width="1680" alt="Screenshot 2023-08-10 at 11 06 49" src="https://github.com/MuhammadSonySetiawan/Peworld/assets/49361887/ec6e92b6-67ef-4938-a6c1-c359d57385bf">

**Comment by MuhammadSonySetiawan** [comment]
add validation email and password
![Screenshot 2023-08-10 114007](https://github.com/MuhammadSonySetiawan/Peworld/assets/132990489/112aaa96-9c97-498e-b074-b106e23271df)
